#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

/** @var \Intisari\Application $app */
$app = require __DIR__ . '/bootstrap/app.php';

$app->loadRoutes($app->routesPath('console.php'));

$status = $app->runConsole();

exit($status);
